# Medical Imaging for Rural Areas - Configuration File

dataset:
  path: "chest_xray_merged"  # Path to the dataset
  classes:
    - "covid"
    - "normal"
    - "pneumonia"
    - "tb"
  train_split: "train"
  val_split: "val"
  test_split: "test"
  
model:
  architectures: 
    - "ResNet50"      # ResNet50 model
    - "DenseNet121"   # DenseNet121 model
    - "EfficientNetB0" # EfficientNet B0 model
  input_size: [224, 224, 3]
  num_classes: 4
  pretrained: true
  fine_tune: true

training:
  batch_size: 16        # Reduced for memory efficiency
  epochs: 25
  learning_rate: 0.001
  weight_decay: 0.0001
  optimizer: "adam"
  scheduler:
    type: "StepLR"
    step_size: 7
    gamma: 0.1

data_augmentation:
  horizontal_flip: true
  rotation: 10        # degrees
  color_jitter:
    brightness: 0.2
    contrast: 0.2
  resize: [256, 256]
  center_crop: [224, 224]

evaluation:
  metrics:
    - "accuracy"
    - "precision"
    - "recall"
    - "f1_score"
    - "confusion_matrix"

device:
  use_cuda: true      # Use GPU if available
  num_workers: 0      # Number of data loader workers (0 for Windows compatibility)

logging:
  log_dir: "logs/"
  save_models: true
  models_dir: "models/"
  plot_training_history: true
  save_confusion_matrix: true

paths:
  dataset_url: "https://www.kaggle.com/datasets/jtiptj/chest-xray-pneumoniacovid19tuberculosis"
  kaggle_dataset: "jtiptj/chest-xray-pneumoniacovid19tuberculosis"